### ISSUE TITLE
Background is not loaded on my device

### ISSUE THREAD

**Issue by remohammadi** [moallemi/persian-calendar-mac-issues#1]
Version: `3.6.1`
macOS Version: `10.13.1 (17B48)`

<img width="853" alt="persiancalendarbug" src="https://user-images.githubusercontent.com/174137/33221507-404d8ac2-d165-11e7-8268-779609d319e9.png">

**Comment by moallemi** [comment]
Go to System Preferences > Accessibility > Display and uncheck `Reduce transparency` if checked.

<img width="780" alt="screen shot 2017-11-26 at 07 39 48" src="https://user-images.githubusercontent.com/1250691/33237052-3de2907a-d27d-11e7-93da-45f5964b281f.png">

**Comment by remohammadi** [comment]
It worked! But now I'm confused about the option! It seems like it works in reverse of what it's suggesting 😝
