### ISSUE TITLE
Wrong year in the menubar and the title

### ISSUE THREAD

**Issue by hamid914** [moallemi/persian-calendar-mac-issues#4]
In the menu bar and the title of the window this date is displayed:
یکشنبه ۲۷ اسفند ۹۷
but it should be:
یکشنبه ۲۷ اسفند ۹۶
In the calendar view, the date is correct.

![bug](https://user-images.githubusercontent.com/1765587/37559711-dc5a6092-2a3f-11e8-9aff-2ee11498272b.jpg)

**Comment by moallemi** [comment]
Thank you for your report.
Fixed in version 3.7.0
