### ISSUE TITLE
Transparent Background in macOS High Sierra (10.13.3)

### ISSUE THREAD

**Issue by mdashti** [moallemi/persian-calendar-mac-issues#5]
<img width="350" alt="screen shot 2018-04-22 at 2 24 17 pm" src="https://user-images.githubusercontent.com/3135608/39093815-a9c306e0-463a-11e8-998e-fe14011e5ccc.png">

It's really hard to see the calendar and there's no option to make the calendar background nontransparent.

**Comment by mdashti** [comment]
<img width="329" alt="screen shot 2018-04-22 at 2 49 49 pm" src="https://user-images.githubusercontent.com/3135608/39093919-7023b9f0-463c-11e8-8590-c694bf8d993b.png">

Maybe this one is a better screenshot to illustrate the issue!

**Comment by moallemi** [comment]
You can temporarily fix this issue with #1 until I found a acceptable solution
